services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/villageos

      - RANDOM_EVENT_CHANCE=${RANDOM_EVENT_CHANCE:-25}
      - COMMAND_COOLDOWN_SOLO_SECONDS=${COMMAND_COOLDOWN_SOLO_SECONDS:-600}
      - COMMAND_COOLDOWN_SOCIAL_SECONDS=${COMMAND_COOLDOWN_SOCIAL_SECONDS:-1800}
      - PORT=${PORT:-3000}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=villageos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
